export const INITIALIZE = "INITIALIZE";
export const INITIALIZE_LOADING = "INITIALIZE_LOADING"; 
export const INITIALIZE_SUCCESS = "INITIALIZE_SUCCESS";
export const INITIALIZE_FAILED = "INITIALIZE_FAILED";

export const ADD_PASSWORD = "ADD_PASSWORD";
export const ADD_PASSWORD_LOADING = "ADD_PASSWORD_LOADING"; 
export const ADD_PASSWORD_SUCCESS = "ADD_PASSWORD_SUCCESS";
export const ADD_PASSWORD_FAILED = "ADD_PASSWORD_FAILED";

export const DELETE_PASSWORDS = "DELETE_PASSWORDS";
export const DELETE_PASSWORDS_LOADING = "DELETE_PASSWORDS_LOADING";
export const DELETE_PASSWORDS_SUCCESS = "DELETE_PASSWORDS_SUCCESS";
export const DELETE_PASSWORDS_FAILED = "DELETE_PASSWORDS_FAILED";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_LOADING = "UPDATE_PASSWORD_LOADING";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";

export const FETCH_PASSWORDS = "FETCH_PASSWORDS";
export const FETCH_PASSWORDS_LOADING = "FETCH_PASSWORDS_LOADING";
export const FETCH_PASSWORDS_SUCCESS = "FETCH_PASSWORDS_SUCCESS";
export const FETCH_PASSWORDS_FAILED = "FETCH_PASSWORDS_FAILED";
